/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.afpa.dahouet.GUI;

import com.afpa.dahouet.dao.ClasseDAO;
import com.afpa.dahouet.dao.JDBCConnect;
import com.afpa.dahouet.dao.PersonneDAO;
import com.afpa.dahouet.dao.ProprietaireDAO;
import com.afpa.dahouet.dao.SerieDAO;
import com.afpa.dahouet.dao.VoilierDAO;
import com.afpa.dahouet.metier.Classe;
import com.afpa.dahouet.metier.Personne;
import com.afpa.dahouet.metier.Proprietaire;
import com.afpa.dahouet.metier.Serie;
import com.afpa.dahouet.metier.Voilier;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sdeniel
 */
public class JFrame extends javax.swing.JFrame {

    // initialisation
    public JFrame() throws SQLException { //java.awt.Frame parent, boolean modal
        
        JDBCConnect jDBCConnect = new JDBCConnect();
        
        initComponents();        
        this.setTitle("Fiche de renseignements"); 
        this.setLocationRelativeTo(null);
        
        invisibleCombo();
          
        
        // ComboBox des series
        List<Serie> nomSeries = SerieDAO.findAll();
        cbSerie.setModel(new javax.swing.DefaultComboBoxModel(nomSeries.toArray()));
    }   
    
    private void invisibleCombo(){
        // Rendre invisible pour la facilité de compréhension de remplissage        
        lblClasse.setVisible(false);
        cbClasse.setVisible(false);
        lblProprietaire.setVisible(false);
        cbProprietaire.setVisible(false);
    }

    // methode de reinitialisation des champs texte
    private void clearChampsDeSaisie() {
        txtNom.setText("");
        txtPrenom.setText("");
        txtEmail.setText("");
        txtNumVoile.setText("");
        txtNumInscription.setText("");
        txtLogin.setText("");
        txtMdp.setText("");
        txtClub.setText("");
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        lblPrenom = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtMdp = new javax.swing.JTextField();
        txtClub = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cbSerie = new javax.swing.JComboBox<>();
        cbClasse = new javax.swing.JComboBox<>();
        lblSerie = new javax.swing.JLabel();
        lblClasse = new javax.swing.JLabel();
        cbProprietaire = new javax.swing.JComboBox<>();
        lblProprietaire = new javax.swing.JLabel();
        txtNumVoile = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumInscription = new javax.swing.JTextField();
        btnAddVoilier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Renseignements Propriétaire"));

        lblEmail.setText("Email");

        lblPrenom.setText("Prenom");

        lblNom.setText("Nom");

        btnAdd.setText("Ajouter Personne");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel3.setText("login (4 chiffres)");

        jLabel4.setText("mdp");

        jLabel5.setText("Club nautique");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrenom)
                            .addComponent(lblNom)
                            .addComponent(lblEmail)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNom)
                            .addComponent(txtEmail)
                            .addComponent(txtPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(txtLogin)
                            .addComponent(txtMdp)
                            .addComponent(txtClub))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNom))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrenom)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(btnAdd)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Renseignements voilier"));

        cbSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSerieActionPerformed(evt);
            }
        });

        cbClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClasseActionPerformed(evt);
            }
        });

        lblSerie.setText("Série");

        lblClasse.setText("Classe");

        cbProprietaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProprietaireActionPerformed(evt);
            }
        });

        lblProprietaire.setText("Proprietaire");

        jLabel1.setText("Numero de voile");

        jLabel2.setText("Numero d'inscription");

        btnAddVoilier.setText("Ajouter Voilier");
        btnAddVoilier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVoilierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAddVoilier)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClasse, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSerie, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProprietaire, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbProprietaire, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbSerie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumInscription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumVoile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumVoile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumInscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerie))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClasse)
                    .addComponent(cbClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProprietaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProprietaire))
                .addGap(31, 31, 31)
                .addComponent(btnAddVoilier)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String nomProp = txtNom.getText();
        String prenomProp = txtPrenom.getText();
        String email = txtEmail.getText();
        String login = txtLogin.getText();
        int identifiant = Integer.parseInt(login);
        String mdp = txtMdp.getText();
        String nomClub = txtClub.getText();
        
        if (nomProp.isEmpty() || prenomProp.isEmpty() || email.isEmpty() || login.isEmpty() || mdp.isEmpty() || nomClub.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs", "ERREUR", JOptionPane.WARNING_MESSAGE);
        } else 
         {
            try {
                
                // Ajout d'une personne
                Personne personne = new Personne(nomProp, prenomProp, email);
                
                PersonneDAO.insert(personne);
                
                Proprietaire proprietaire = new Proprietaire(identifiant, mdp, nomClub, personne.getPersonneID() );
                ProprietaireDAO.insert(proprietaire);
                                
                JOptionPane.showMessageDialog(null, "Proprietaire ajouté dans la base de données");
                
                clearChampsDeSaisie();
                txtNumVoile.requestFocus();
                invisibleCombo();
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERREUR générale en fin d'insertion", "ERREUR", JOptionPane.WARNING_MESSAGE);
            }
         }        
    }//GEN-LAST:event_btnAddActionPerformed

    private void cbSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSerieActionPerformed
        
         Object nomSeries = cbSerie.getSelectedItem();
         Serie listeSeries = (Serie) nomSeries;
         
         int  choixSerie = listeSeries.getSerieID();
         lblClasse.setVisible(true);
         cbClasse.setVisible(true);   
         
         List<Classe> nomClasse = ClasseDAO.findAll(choixSerie);
         cbClasse.setModel(new javax.swing.DefaultComboBoxModel(nomClasse.toArray()));
                
    }//GEN-LAST:event_cbSerieActionPerformed

    private void btnAddVoilierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVoilierActionPerformed
         // Remplissage des textfields
         String nomVoilier = txtNumVoile.getText();
         String numInscription = txtNumInscription.getText();
         
         // Choix des combobox classe et proprietaire
         Object listeClasse = cbClasse.getSelectedItem();
         Classe classe = (Classe) listeClasse;
         Object listeProprietaire = cbProprietaire.getSelectedItem();
         Proprietaire proprietaire = (Proprietaire) listeProprietaire;
         
         if (nomVoilier.isEmpty() || numInscription.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs", "ERREUR", JOptionPane.WARNING_MESSAGE);
        } else 
         {
            try {
                Voilier voilier = new Voilier(nomVoilier, numInscription, proprietaire.getIdentifiant(), proprietaire.getPersonneID(), classe.getClasseID());
                VoilierDAO.insert(voilier);
                
                JOptionPane.showMessageDialog(null, "Voilier inséré dans la base de données");
                clearChampsDeSaisie();
                txtNumVoile.requestFocus();
                invisibleCombo();
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERREUR", "ERREUR", JOptionPane.WARNING_MESSAGE);
            }
         }
         
        
    }//GEN-LAST:event_btnAddVoilierActionPerformed

    private void cbClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClasseActionPerformed
           
         lblProprietaire.setVisible(true);
         cbProprietaire.setVisible(true);
         
         List<Proprietaire> nomProprietaire = ProprietaireDAO.findAll();
         cbProprietaire.setModel(new javax.swing.DefaultComboBoxModel(nomProprietaire.toArray()));
         
    }//GEN-LAST:event_cbClasseActionPerformed

    private void cbProprietaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProprietaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProprietaireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddVoilier;
    private javax.swing.JComboBox<String> cbClasse;
    private javax.swing.JComboBox<String> cbProprietaire;
    private javax.swing.JComboBox<String> cbSerie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblClasse;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JLabel lblProprietaire;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JTextField txtClub;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtMdp;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumInscription;
    private javax.swing.JTextField txtNumVoile;
    private javax.swing.JTextField txtPrenom;
    // End of variables declaration//GEN-END:variables
}
